# Generated by Django 3.1.7 on 2021-04-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_User_Info',
            fields=[
                ('user_name', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=100)),
                ('user_birth', models.IntegerField()),
                ('user_call', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_subject', models.CharField(max_length=50)),
                ('notice_memo', models.CharField(max_length=3000)),
                ('regist_dt', models.DateField()),
                ('regist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.test_user_info')),
            ],
        ),
    ]
